name: Tests

on:
  push:
    branches:
      - master
      - dev
      - fix
      - feat
      - tmp

jobs:
  setup_matrix_for_centOS:
    name: Setup matrix for centOS
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo 'matrix=["centos:centos8.4.2105", "centos:centos8"]' >> $GITHUB_OUTPUT
  unit_test_on_centOS:
    name: Unit est on centOS
    needs:
      - setup_matrix_for_centOS
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        centos: ${{fromJson(needs.setup_matrix_for_centOS.outputs.matrix)}}
    env:
      CENTOS_VERSION: ${{ matrix.centos }}
    steps:
      - name: Set container name
        id: vars
        run: |
          echo "CONTAINER_NAME=centos" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Conf the yum repository
        run: |
          docker run -itd -v $PWD:/workdir --name ${CONTAINER_NAME} -w /workdir ${CENTOS_VERSION}
          docker exec ${CONTAINER_NAME} bash -c "
            cd /etc/yum.repos.d/ && rm -rf * .??* && cd -
            cat .github/workflows/CentOS-Base.repo > /etc/yum.repos.d/CentOS-Base.repo
            cat /etc/yum.repos.d/CentOS-Base.repo
          "
      - name: Unit test
        run: |
          docker exec ${CONTAINER_NAME} bash -c "
            yum install -y make zsh
            export PATH=${PATH}:$(pwd)/bin
            make unit-test
          "
      - name: Integration test
        run: |
          docker exec ${CONTAINER_NAME} bash -c "
            export PATH=${PATH}:$(pwd)/bin
            make integration-test
          "
