name: Tests

on:
  push:
    branches:
      - master
      - dev
      - fix
      - feat
      - tmp

jobs:
  qjs-tools-test:
    # runs on node 21 on container
    container: node:20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install pnpm
        run: |
          npm install -g pnpm
      - name: Install dependencies
        run: |
          pnpm install
      - name: Run tests
        run: |
          cd src/qjs-tools
          pnpm run test

  setup_matrix_for_centOS:
    name: Setup matrix for centOS
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo 'matrix=["centos:centos8.4.2105", "centos:centos8"]' >> $GITHUB_OUTPUT
  unit_test_on_centOS:
    name: Unit est on centOS
    needs:
      - setup_matrix_for_centOS
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        centos: ${{fromJson(needs.setup_matrix_for_centOS.outputs.matrix)}}
    env:
      CENTOS_VERSION: ${{ matrix.centos }}
    steps:
      - name: Set container name
        id: vars
        run: |
          echo "CONTAINER_NAME=centos" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Conf the yum repository
        run: |
          docker run -itd -v $PWD:/workdir --name ${CONTAINER_NAME} -w /workdir ${CENTOS_VERSION}
          docker exec ${CONTAINER_NAME} bash -c "
            cd /etc/yum.repos.d/ && rm -rf * .??* && cd -
            cat .github/workflows/CentOS-Base.repo > /etc/yum.repos.d/CentOS-Base.repo
            cat /etc/yum.repos.d/CentOS-Base.repo
          "
      - name: Unit test
        run: |
          docker exec ${CONTAINER_NAME} bash -c "
            yum install -y make zsh;
            export PATH=\${PATH}:\$(pwd)/bin;
            bin/qjs --version
            make unit-test;
          "
      - name: Integration test
        run: |
          docker exec ${CONTAINER_NAME} bash -c "
            export PATH=\${PATH}:\$(pwd)/bin;
            make integration-test;
          "
  macos_x86:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Run commands on macOS
        run: |
          export PATH=${PATH}:$(pwd)/bin;
          make test
